name: foo_form_field
description: Reusable Flutter FormFields and formatters for integer-only input.
version: 1.0.0-beta.2
homepage: https://github.com/BaselMoustafa/foo_form_field
repository: https://github.com/BaselMoustafa/foo_form_field
documentation: https://github.com/BaselMoustafa/foo_form_field#readme
issue_tracker: https://github.com/BaselMoustafa/foo_form_field/issues
topics:
  - form
  - fields
  - validation
  - form_fields
  - form_input


environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
